apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reboot-controller
  namespace: reboot-operator
spec:
  selector:
    matchLabels:
      app: reboot-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: reboot-controller
    spec:
      containers:
      - name: reboot-controller
        image: jamiehannaford/reboot-controller
        imagePullPolicy: Always
        command:
        - /reboot-controller
        - --v=4
